- name: Create an empty file to prevent the service from starting
  file:
    path: /etc/cloud/cloud-init.disabled
    state: touch
  ignore_errors: yes

- name: Disable all services (uncheck everything except "None")
  shell: dpkg-reconfigure -f noninteractive cloud-init
  ignore_errors: yes

- name: Uninstall cloud-init
  apt:
    name: cloud-init
    state: absent
    purge: yes

- file:
    path: "{{ item }}"
    state: absent
  with_items: 
    - /etc/cloud
    - /var/lib/cloud

- name: Install netplan
  apt:
    name: netplan.io
    state: present
    update_cache: yes

- name: Set fixed static IP
  template:
    src: "{{ role_path }}/templates/network.j2"
    dest: /etc/netplan/50-cloud-init.yaml

# - name: test configurations
#   shell: netplan try
#   register: nettry_out

# - debug:
#     msg: "{{ nettry_out }}"

- name: apply the changes
  shell: netplan apply
  register: netapp_out

- debug:
    msg: "{{ netapp_out }}"

- name: Install resolvconf
  apt:
    name: resolvconf
    state: present
    update_cache: yes

- name: Set DNS server as 8.8.8.8 and 8.8.4.4
  lineinfile:
    path: /etc/resolvconf/resolv.conf.d/head
    regexp: '{{ item }}'
    line: '{{ item }}'
  with_items:
    - nameserver 8.8.8.8
    - nameserver 8.8.4.4

- name: Run the resolv.conf update
  shell: "{{ item }}"
  with_items: 
    - resolvconf --enable-updates
    - resolvconf -u

- name: Deploy ClamAV
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - clamav
    - clamav-daemon
  
- name: Update Signature Database with clamav-freshclam
  systemd: 
    name: clamav-freshclam
    state: stopped

- shell: freshclam

- name: Start the clamav-freshclam service
  systemd: 
    name: clamav-freshclam
    state: started

- name: create a file /root/clamv_night_check.sh
  copy:
    src: "{{ role_path }}/files/clamv_night_check.sh"
    dest: /root/clamv_night_check.sh

- name: Create a cron job
  cron:
    name: "Scan Network"
    hour: "4"
    job: "/root/clamv_night_check.sh"

- name: Edit the /etc/clamav/clamd.conf configuration file
  lineinfile:
    path: /etc/clamav/clamd.conf
    regexp: '{{ item }}'
    line: '{{ item }}'
  with_items:
    - ScanOnAccess true
    - OnAccessIncludePath /
    - OnAccessExcludePath /var/log  
    - OnAccessPrevention yes
    - OnAccessExtraScanning true
    - OnAccessExcludeUID 0
- name: Change clamd user       
  replace:
    path: /etc/clamav/clamd.conf
    regexp: 'User clamav'
    replace: "User root"

